#!/bin/sh

# wait until plaback controller is available
#while true; do
#  RET=$(curl http://localhost:81/playback/main -s -o /dev/null -w "%{http_code}")
#  if [ "$RET" = "200" ]; then
#    break
#  fi
#  >&2 echo "husar display playback not yet ready to display; waiting for 5s"
#  sleep 5
#done

xset s off
xset s noblank
xset -dpms
xrandr --output HDMI-1 --mode 800x600 # --rate 23.98
# Enable closing X with ctrl + alt + backspace
#setxkbmap -option "terminate:ctrl_alt_bksp"

# Preprocess chromium configuration
#sed -i 's/"exited_cleanly":false/"exited_cleanly":true/' $HOME/.config/chromium/Default/Preferences

#if [ -e "$HOME/.config/chromium/SingletonLock" ]; then
#  rm "$HOME/.config/chromium/SingletonLock"
#fi

#exec chromium \
#    --noerrdialogs --bwsi --disable-autofill-keyboard-accessory-view --disable-contextual-search --disable-extensions \
#    --disable --disable-translate --disable-infobars --disable-suggestions-service --disable-save-password-bubble \
#    --disable-gaia-services --disable-notifications --disable-suggestions-ui --disable-sync \
#    --disable-pinch --overscroll-history-navigation=0 --no-user-gesture-required \
#    --check-for-update-interval=126144000 \
#    --window-position=0,0 --window-size="1920,1080" --disable-new-profile-management --ignore-user-profile-mapping-for-tests \
#    --enable-kiosk-mode --kiosk http://localhost:81/playback/main --incognito
