version: '2.'
services:

  GUIsocket:
    image: "suchy1105/guisocket"
    container_name: GUIapi

  - .:/src/csdip-detector
    - ../csdip:/src/csdip
    - $GOPATH/pkg/mod/cache/download:/go/pkg/mod/cache/download
    command: sh -c "cd /src/csdip-detector && make clean && make build"
