version: '2.4'
services:
  GUIcontroll:
    image: "guiimage:latest"
    #env_file:
    #  - /etc/hae/config/env/hae.env
    environment:
      - DISPLAY=${DISPLAY}
    privileged: true
    restart: always
    volumes:
      - ~/.Xauthority:/root/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/app
      - "/usr/bin/xrandr:/usr/bin/xrandr"
 #     - $GOPATH/pkg/mod/cache/download:/go/pkg/mod/cache/download
    ports:
      - 1551:1551
      - 8081:8081
    container_name: GUIcontroll
    #network_mode: "host"
